# Generated by Django 6.0.1 on 2026-02-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='recipepost',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='recipepost',
            name='summary',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
