# Generated by Django 6.0.1 on 2026-02-19 13:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_options_alter_recipepost_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepost',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
