# Generated by Django 6.0.1 on 2026-02-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_remove_userprofile_posts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='full_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
